'use client';
import {useState,useEffect,useMemo} from 'react';
import dynamic from 'next/dynamic';
import {MapPin,Route,Clock,ChevronRight,Phone,ArrowUpRight,Check,RotateCcw,Sun,Info,Download} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import snapshot from '@/lib/navagraha/road-snapshot.json';
import {temples,bases,sourceDate} from '@/lib/navagraha/data';
import {planTrip,estimatedMatrix,formatTime,type Settings,type Plan} from '@/lib/navagraha/planner';
const TempleMap=dynamic(()=>import('@/components/temple-map'),{ssr:false,loading:()=> <div className="map-loading">Loading temple map…</div>});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const defaultSettings=():Settings=>({base:9,days:2,start:360,end:1200,pace:'normal',date:today()});
export default function Home(){
 const [ta,setTa]=useState(false),[settings,setSettings]=useState<Settings>(defaultSettings),[plan,setPlan]=useState<Plan|null>(null),[activeSettings,setActiveSettings]=useState<Settings>(defaultSettings),[day,setDay]=useState('0'),[selected,setSelected]=useState<number|null>(null),[completed,setCompleted]=useState<number[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[matrix,setMatrix]=useState(snapshot.matrix),[road,setRoad]=useState(true),[loaded,setLoaded]=useState(false),[tab,setTab]=useState('plan');
 const t=(en:string,taText:string)=>ta?taText:en;
 useEffect(()=>{try{const raw=localStorage.getItem('navagraha-v1');if(raw){const d=JSON.parse(raw);if(d.version===1&&d.settings&&d.plan&&Array.isArray(d.completed)&&d.plan.stops?.every((s:{index:number})=>Number.isInteger(s.index)&&s.index>=0&&s.index<9)&&[9,10,11].includes(d.settings.base)){setSettings(d.settings);setActiveSettings(d.settings);setPlan(d.plan);setCompleted(d.completed);setRoad(d.road===true);setMessage('Saved trip restored. Generate a new plan to refresh road estimates.');}}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded&&plan){try{localStorage.setItem('navagraha-v1',JSON.stringify({version:1,settings:activeSettings,plan,completed,road}));}catch{setMessage('Browser storage is unavailable. Keep this tab open.');}}},[loaded,plan,completed,activeSettings,road]);
 const stops=useMemo(()=>plan?.stops.filter(s=>s.day===Number(day))??[],[plan,day]);const temple=selected===null?null:temples[selected];
 async function generate(replan=false){setBusy(true);setMessage('');await new Promise(r=>setTimeout(r,20));try{let m=matrix;let isRoad=road;try{const res=await fetch('/api/travel',{signal:AbortSignal.timeout(14000)});if(!res.ok)throw Error();const d=await res.json() as {matrix:number[][]};m=d.matrix;setMatrix(m);isRoad=true;setRoad(true);}catch{m=snapshot.matrix;setMatrix(m);isRoad=true;setRoad(true);}const s=replan?activeSettings:settings;const prefix=replan?plan?.stops.filter(x=>completed.includes(x.index))??[]:[];const next=planTrip(s,m,prefix,replan?90:0);setPlan(next);setActiveSettings(s);if(!replan){setCompleted([]);setDay('0');}else setDay(String(prefix.at(-1)?.day??0));setTab('plan');setMessage(!isRoad?t('Road service unavailable. This is a rough distance-based draft; verify driving times before travel.','சாலை சேவை கிடைக்கவில்லை. தோராயமான பயண நேரங்களைப் பயணத்திற்கு முன் சரிபார்க்கவும்.'):replan?t('Remaining visits updated with a 90-minute delay.','90 நிமிட தாமதத்துடன் மீதமுள்ள பயணம் புதுப்பிக்கப்பட்டது.'):t('Plan ready. Call temples to confirm hours before travel.','திட்டம் தயார். பயணத்திற்கு முன் கோவில் நேரங்களை உறுதி செய்யவும்.'));}catch{setMessage(t('Could not create this trip. Check dates and daily start/end times.','திட்டமிட முடியவில்லை. தேதி மற்றும் நேரங்களைச் சரிபார்க்கவும்.'));}finally{setBusy(false);}}
 function complete(index:number){if(completed.includes(index)){const pos=completed.indexOf(index);setCompleted(completed.slice(0,pos));return;}const next=plan?.stops.find(x=>!completed.includes(x.index));if(next?.index!==index){setMessage(t('Mark visits complete in itinerary order.','பயண வரிசைப்படி வருகையை நிறைவு செய்யவும்.'));return;}setCompleted([...completed,index]);}
 function download(){if(!plan)return;const lines=['NAVAGRAHA PILGRIMAGE',activeSettings.date,`Base: ${bases[activeSettings.base-9].name}`,road?'OSRM road estimates; no live traffic':'Rough distance-based draft','Hours and entrances need confirmation.',''];for(let i=0;i<activeSettings.days;i++){lines.push(`DAY ${i+1}`);plan.stops.filter(s=>s.day===i).forEach(s=>lines.push(`${formatTime(s.arrival)} — ${temples[s.index].name} (${temples[s.index].graha}); depart ${formatTime(s.departure)}; phone ${temples[s.index].phone}`));const ret=plan.returns.find(r=>r.day===i);if(ret)lines.push(`Return to base ${formatTime(ret.arrival)}`);lines.push('');}if(plan.missing.length)lines.push('UNSCHEDULED: '+plan.missing.map(i=>temples[i].name).join(', '));const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='navagraha-trip.txt';a.click();URL.revokeObjectURL(url);}
 return <main className="app"><header className="topbar"><div className="brand"><span className="brandmark"><Sun size={23}/></span><div><h1>{t('Navagraha','நவக்கிரக யாத்திரை')}</h1><span>META MUDHALEEDU</span></div></div><div className="toplinks"><span className="version">{t('Pilgrimage planner','புனிதப் பயணத் திட்டம்')}</span><button className="language" onClick={()=>setTa(!ta)}>{ta?'English':'தமிழ்'}</button></div></header>
 <div className="workspace"><aside className="sidebar"><div className="intro"><span className="eyebrow">{t('CAUVERY DELTA CIRCUIT','காவிரி டெல்டா சுற்றுலா')}</span><h2>{t('Nine temples. Your journey.','ஒன்பது கோவில்கள். உங்கள் பயணம்.')}</h2><p>{t('Plan your darshan, with room to breathe.','நிதானமான தரிசனத்திற்குத் திட்டமிடுங்கள்.')}</p></div>
 <section className="trip-form" aria-label="Trip preferences"><div className="form-row"><label>{t('Starting town','தொடங்கும் ஊர்')}<Select value={String(settings.base)} onValueChange={v=>setSettings({...settings,base:Number(v)})}><SelectTrigger aria-label="Starting town"><SelectValue/></SelectTrigger><SelectContent>{bases.map((b,i)=><SelectItem key={b.id} value={String(i+9)}>{ta?b.ta:b.name}</SelectItem>)}</SelectContent></Select></label><label>{t('Travel date','பயண தேதி')}<input aria-label="Travel date" type="date" value={settings.date} onChange={e=>setSettings({...settings,date:e.target.value})}/></label></div>
 <div className="form-row"><label>{t('Trip length','பயண நாட்கள்')}<Select value={String(settings.days)} onValueChange={v=>setSettings({...settings,days:Number(v)})}><SelectTrigger aria-label="Trip length"><SelectValue/></SelectTrigger><SelectContent>{[1,2,3].map(n=><SelectItem value={String(n)} key={n}>{n} {t(n===1?'day':'days','நாள்')}</SelectItem>)}</SelectContent></Select></label><label>{t('Your pace','பயண வேகம்')}<Select value={settings.pace} onValueChange={v=>setSettings({...settings,pace:v as Settings['pace']})}><SelectTrigger aria-label="Your pace"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="express">{t('Express · 30 min','விரைவு · 30 நிமி')}</SelectItem><SelectItem value="normal">{t('Balanced · 45 min','இயல்பு · 45 நிமி')}</SelectItem><SelectItem value="relaxed">{t('Relaxed · 65 min','நிதானம் · 65 நிமி')}</SelectItem></SelectContent></Select></label></div>
 <div className="form-row"><label>{t('Start each day','புறப்படும் நேரம்')}<input aria-label="Daily start time" type="time" value={`${String(Math.floor(settings.start/60)).padStart(2,'0')}:${String(settings.start%60).padStart(2,'0')}`} onChange={e=>{const [h,m]=e.target.value.split(':').map(Number);setSettings({...settings,start:h*60+m});}}/></label><label>{t('Back by','திரும்பும் நேரம்')}<input aria-label="Daily end time" type="time" value={`${String(Math.floor(settings.end/60)).padStart(2,'0')}:${String(settings.end%60).padStart(2,'0')}`} onChange={e=>{const [h,m]=e.target.value.split(':').map(Number);setSettings({...settings,end:h*60+m});}}/></label></div>
 <p className="form-note">{t('By car · return to your starting town nightly · 45-min lunch','கார் பயணம் · இரவில் தொடங்கிய ஊருக்குத் திரும்புதல் · 45 நிமிட மதிய உணவு')}</p><button className="primary" disabled={busy||!settings.date||!Number.isFinite(settings.start)||!Number.isFinite(settings.end)||settings.start>=settings.end} onClick={()=>generate()}><Route size={18}/>{busy?t('Planning your route…','திட்டமிடப்படுகிறது…'):t(plan?'Generate new plan':'Plan my journey',plan?'புதிய திட்டம்':'எனது பயணத்தைத் திட்டமிடு')}<ChevronRight size={18}/></button></section>
 {message&&<div className="notice" role="status"><Info size={16}/><span>{message}</span></div>}
 <Tabs value={tab} onValueChange={setTab} className="content-tabs"><TabsList variant="line"><TabsTrigger value="plan">{t('Itinerary','பயணத் திட்டம்')}</TabsTrigger><TabsTrigger value="temples">{t('All temples','அனைத்து கோவில்கள்')} <span className="count">9</span></TabsTrigger></TabsList></Tabs>
 <div className="results">{tab==='temples'?temples.map((t0,i)=><button className={'temple-row '+(selected===i?'selected':'')} key={t0.id} onClick={()=>setSelected(i)}><span className="number">{i+1}</span><span><strong>{ta?t0.ta:t0.name}</strong><small>{ta?t0.grahaTa:t0.graha}</small></span><ChevronRight size={16}/></button>):!plan?<div className="empty"><Route size={30}/><h3>{t('A route made for your day','உங்கள் நாளுக்கேற்ற பயணம்')}</h3><p>{t('Choose your dates and pace above. We’ll fit all nine temples around their opening windows.','தேதி மற்றும் வேகத்தைத் தேர்ந்தெடுக்கவும். கோவில் நேரங்களுக்கேற்ற திட்டத்தை உருவாக்குவோம்.')}</p><div className="empty-facts"><span>9 {t('temples','கோவில்கள்')}</span><span>1–3 {t('days','நாட்கள்')}</span><span>{t('Basic darshan','தரிசனம்')}</span></div></div>:<><div className="plan-summary"><div><strong>{plan.stops.length}/9</strong><span>{t('scheduled','திட்டமிட்டவை')}</span></div><div><strong>{Math.floor(plan.drive/60)}h {plan.drive%60}m</strong><span>{t('driving estimate','பயண நேரம்')}</span></div><button className="icon-button" title="Download itinerary" aria-label="Download itinerary" onClick={download}><Download size={19}/></button></div><p className="estimate-label">{road?t('OSRM estimates + buffer · cached if offline · no live traffic','சாலை நேரம் + இடைவெளி · நேரடி போக்குவரத்து இல்லை'):t('Rough distance-based draft · check road times','தோராயமான திட்டம் · சாலை நேரங்களைச் சரிபார்க்கவும்')}</p>{!plan.complete&&<div className="conflict" role="alert"><strong>{t('All nine do not fit this draft.','ஒன்பதும் இத்திட்டத்தில் பொருந்தவில்லை.')}</strong><p>{t('Try another day, earlier start, or faster pace. Unscheduled: ','கூடுதல் நாள் அல்லது நேரத்தை முயற்சிக்கவும். விடுபட்டவை: ')}{plan.missing.map(i=>ta?temples[i].ta:temples[i].name).join(', ')}</p></div>}
 <Tabs value={day} onValueChange={setDay}><TabsList className="day-tabs">{Array.from({length:activeSettings.days},(_,i)=><TabsTrigger key={i} value={String(i)}>{t('Day','நாள்')} {i+1}</TabsTrigger>)}</TabsList></Tabs>
 {plan.lateReturn&&<div className="conflict" role="alert">{t('The delay pushes your return past the daily deadline. Remaining visits use later days where possible.','தாமதத்தால் திரும்பும் நேரம் கடந்துவிடும். மீதமுள்ள வருகைகள் அடுத்த நாட்களில் திட்டமிடப்படும்.')}</div>}<div className="timeline"><div className="day-origin"><MapPin size={15}/>{ta?bases[activeSettings.base-9].ta:bases[activeSettings.base-9].name}<span>{formatTime(activeSettings.start)}</span></div>{stops.map(s=><div className={'stop '+(selected===s.index?'active':'')} key={s.index}>{s.lunch&&<div className="break-label">{t('45-min lunch before this visit','இதற்கு முன் 45 நிமிட மதிய உணவு')}</div>}<div className="travel"><span/>{s.drive} {t('min drive','நிமிட பயணம்')}{s.wait>0&&` · ${s.wait} ${t('min wait','நிமிட காத்திருப்பு')}`}</div><div className="stop-line"><button className={'check-stop '+(completed.includes(s.index)?'checked':'')} aria-label={`Mark ${temples[s.index].name} complete`} onClick={()=>complete(s.index)}>{completed.includes(s.index)?<Check size={14}/>:stops.findIndex(x=>x.index===s.index)+1}</button><button className="stop-info" onClick={()=>setSelected(s.index)}><div className="stop-time">{formatTime(s.arrival)} <span>– {formatTime(s.departure)}</span></div><strong>{ta?temples[s.index].ta:temples[s.index].name}</strong><small>{ta?temples[s.index].grahaTa:temples[s.index].graha}</small></button><a className="navigate" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(temples[s.index].name+' temple Tamil Nadu')}&travelmode=driving`} target="_blank" rel="noreferrer" title="Open directions" aria-label={`Directions to ${temples[s.index].name}`}><ArrowUpRight size={18}/></a></div></div>)}{!stops.length&&<p className="muted">{t('No visits scheduled on this day.','இந்த நாளில் வருகைகள் இல்லை.')}</p>}{plan.returns.filter(r=>r.day===Number(day)).map(r=><div className="day-origin return" key={r.day}><MapPin size={15}/>{t('Back to base','ஊருக்குத் திரும்புதல்')}<span>{formatTime(r.arrival)}</span></div>)}</div>
 <button className="secondary" disabled={busy||completed.length===0||completed.length===9} onClick={()=>generate(true)}><RotateCcw size={16}/>{t('Running 90 min late? Replan','90 நிமிட தாமதமா? மீண்டும் திட்டமிடு')}</button><p className="storage-note">{t(`${completed.length} completed · saved on this browser`,`${completed.length} நிறைவு · இந்த உலாவியில் சேமிக்கப்பட்டது`)}</p></>}</div>
 <footer className="sidebar-footer">{t('Basic darshan only. Special rituals need a separate plan.','தரிசனம் மட்டும். சிறப்பு பூஜைகளுக்குத் தனித் திட்டம் தேவை.')}</footer></aside>
 <section className="map-panel" aria-label="Temple map"><TempleMap selected={selected} onSelect={setSelected} stops={stops} base={activeSettings.base} completed={completed} ta={ta}/><div className="map-heading"><span className="eyebrow">{t('EXPLORE THE CIRCUIT','பயணச் சுற்றை ஆராயுங்கள்')}</span><h2>{t('The nine sacred stops','ஒன்பது புனிதத் தலங்கள்')}</h2><p>{t('Thanjavur · Kumbakonam · Karaikal','தஞ்சாவூர் · கும்பகோணம் · காரைக்கால்')}</p></div>{temple&&<div className="detail-card"><button className="close-detail" onClick={()=>setSelected(null)} aria-label="Close temple details">×</button><span className="eyebrow">{ta?temple.grahaTa:temple.graha}</span><h2>{ta?temple.ta:temple.name}</h2><p className="hours"><Clock size={16}/>{temple.hours.map(([a,b])=>`${formatTime(a)} – ${formatTime(b)}`).join(' / ')}</p><p>{temple.note}</p><p className="source-note">{t('Seed guide: ','வழிகாட்டி: ')}{sourceDate}. {t('Confirm hours before travel.','நேரங்களை உறுதி செய்யவும்.')}</p><div className="detail-actions"><a href={`tel:${temple.phone}`}><Phone size={15}/>{t('Call temple','அழைக்கவும்')}</a><a href={temple.source} target="_blank" rel="noreferrer">{t('Source','ஆதாரம்')}<ArrowUpRight size={15}/></a></div></div>}</section></div></main>;
}
