'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LMap,LayerGroup} from 'leaflet';
import {temples,bases,points} from '@/lib/navagraha/data';
import type {Stop} from '@/lib/navagraha/planner';
import 'leaflet/dist/leaflet.css';
export default function TempleMap({selected,onSelect,stops,base,completed,ta}:{selected:number|null;onSelect:(n:number)=>void;stops:Stop[];base:number;completed:number[];ta:boolean}){
 const routeCache=useRef<Record<string,number[][]>>({});
 const el=useRef<HTMLDivElement>(null), map=useRef<LMap|null>(null), layers=useRef<LayerGroup|null>(null);const [ready,setReady]=useState(false);const [routeState,setRouteState]=useState('');const select=useRef(onSelect);select.current=onSelect;
 useEffect(()=>{let alive=true;import('leaflet').then(L=>{if(!alive||!el.current)return;const m=L.map(el.current,{zoomControl:false}).setView([11.015,79.46],10);map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:18}).addTo(m);layers.current=L.layerGroup().addTo(m);setReady(true);});return()=>{alive=false;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready)return;let cancelled=false;const controller=new AbortController();import('leaflet').then(async L=>{if(!layers.current||!map.current)return;layers.current.clearLayers();temples.forEach((t,i)=>{const order=stops.findIndex(s=>s.index===i);const chosen=selected===i;const done=completed.includes(i);const icon=L.divIcon({className:'pin-wrap',html:`<span class="temple-pin ${chosen?'chosen':''} ${done?'done':''}"><b>${done?'✓':order>=0?order+1:stops.length?'•':i+1}</b></span>`,iconSize:[36,40],iconAnchor:[18,36]});const marker=L.marker([t.lat,t.lng],{icon,keyboard:true,title:t.name}).addTo(layers.current!);marker.bindTooltip(ta?t.ta:t.name,{direction:'top',offset:[0,-35]});marker.on('click',()=>select.current(i));});const b=bases[base-9];L.circleMarker([b.lat,b.lng],{radius:7,color:'#142c44',fillColor:'#fff',fillOpacity:1,weight:3}).bindTooltip(b.name).addTo(layers.current);
 if(stops.length){const ids=[base,...stops.map(x=>x.index),base];setRouteState(ta?'பாதை ஏற்றப்படுகிறது…':'Loading road route…');try{let coords=routeCache.current[ids.join(',')];if(!coords){try{const r=await fetch('/api/route?stops='+ids.join(','),{signal:controller.signal});if(!r.ok)throw Error();const data=await r.json() as {coordinates:number[][]};coords=data.coordinates;}catch{if(cancelled)return;const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+ids.map(i=>points[i].lng+','+points[i].lat).join(';')+'?overview=full&geometries=geojson',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const data=await r.json() as {routes:{geometry:{coordinates:number[][]}}[]};coords=data.routes[0].geometry.coordinates;}routeCache.current[ids.join(',')]=coords;}const data={coordinates:coords};if(cancelled)return;L.polyline(data.coordinates.map((v:number[])=>[v[1],v[0]]),{color:'#b65d28',weight:4,opacity:.85}).addTo(layers.current!);setRouteState(ta?'சாலைப் பாதை · நேரடி போக்குவரத்து இல்லை':'Road route · no live traffic');}catch{if(cancelled)return;L.polyline(ids.map(i=>i<9?[temples[i].lat,temples[i].lng]:[b.lat,b.lng]) as [number,number][],{color:'#b65d28',weight:3,dashArray:'7 8'}).addTo(layers.current!);setRouteState(ta?'இணைப்புக் கோடு மட்டும் · சாலைப் பாதை இல்லை':'Connection line only · road route unavailable');}}
 else setRouteState(ta?'ஒன்பது நவக்கிரகத் தலங்கள்':'Nine Navagraha temples');});return()=>{cancelled=true;controller.abort();};},[ready,stops,base,selected,completed,ta]);
 return <div className="map-shell"><div ref={el} className="map-canvas" aria-label="Interactive Navagraha temple map"/><div className="map-caption"><span className="route-swatch"/>{routeState||'Loading map…'}</div><button className="map-reset" onClick={()=>map.current?.fitBounds([[10.76,79.07],[11.22,79.87]],{padding:[45,45]})}>{ta?'அனைத்தையும் காட்டு':'Show all temples'}</button><div className="map-note">{ta?'கோவில் இருப்பிடங்கள் தோராயமானவை. நுழைவாயில்கள் உறுதி செய்யப்படவில்லை.':'Approximate temple locations. Entrances are not yet verified.'}</div></div>;
}
